<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *
*/

declare(strict_types=1);

namespace pocketmine\network\mcpe\multiversion;

use pocketmine\network\mcpe\protocol\ProtocolInfo;

abstract class ProtocolConvertor{
    /**
     * @param int $playerProtocol
     * 
     * @return int
     */
	public final static function convertProtocol(int $playerProtocol) : int{
		switch($playerProtocol){
			case ProtocolInfo::PROTOCOL_800:
				return ProtocolInfo::PROTOCOL_800;
			case ProtocolInfo::PROTOCOL_786:
				return ProtocolInfo::PROTOCOL_786;
			case ProtocolInfo::PROTOCOL_776:
				return ProtocolInfo::PROTOCOL_776;
			case ProtocolInfo::PROTOCOL_766:
				return ProtocolInfo::PROTOCOL_766;
			case ProtocolInfo::PROTOCOL_748:
				return ProtocolInfo::PROTOCOL_748;
			case ProtocolInfo::PROTOCOL_729:
				return ProtocolInfo::PROTOCOL_729;
			case ProtocolInfo::PROTOCOL_712:
                return ProtocolInfo::PROTOCOL_712;
			case ProtocolInfo::PROTOCOL_686:
			    return ProtocolInfo::PROTOCOL_686;
			case ProtocolInfo::PROTOCOL_685:
			    return ProtocolInfo::PROTOCOL_685;
			case ProtocolInfo::PROTOCOL_671:
			    return ProtocolInfo::PROTOCOL_671;
			case ProtocolInfo::PROTOCOL_662:
			    return ProtocolInfo::PROTOCOL_662;
			case ProtocolInfo::PROTOCOL_649:
			    return ProtocolInfo::PROTOCOL_649;
			case ProtocolInfo::PROTOCOL_630:
			    return ProtocolInfo::PROTOCOL_630;
			case ProtocolInfo::PROTOCOL_622:
			    return ProtocolInfo::PROTOCOL_622;
			case ProtocolInfo::PROTOCOL_618:
			    return ProtocolInfo::PROTOCOL_618;
			case ProtocolInfo::PROTOCOL_594:
			    return ProtocolInfo::PROTOCOL_594;
			case ProtocolInfo::PROTOCOL_589:
			    return ProtocolInfo::PROTOCOL_589;
			case ProtocolInfo::PROTOCOL_582:
			    return ProtocolInfo::PROTOCOL_582;
			case ProtocolInfo::PROTOCOL_575:
			    return ProtocolInfo::PROTOCOL_575;
			case ProtocolInfo::PROTOCOL_568:
			    return ProtocolInfo::PROTOCOL_568;
			case ProtocolInfo::PROTOCOL_567:
				return ProtocolInfo::PROTOCOL_567;
			case ProtocolInfo::PROTOCOL_560:
				return ProtocolInfo::PROTOCOL_560;
			case ProtocolInfo::PROTOCOL_557:
				return ProtocolInfo::PROTOCOL_557;
			case ProtocolInfo::PROTOCOL_554:
			case ProtocolInfo::PROTOCOL_553:
				return ProtocolInfo::PROTOCOL_553;
			case ProtocolInfo::PROTOCOL_545:
			case ProtocolInfo::PROTOCOL_544:
				return ProtocolInfo::PROTOCOL_544;
			case ProtocolInfo::PROTOCOL_534:
				return ProtocolInfo::PROTOCOL_534;
			case ProtocolInfo::PROTOCOL_527:
			case ProtocolInfo::PROTOCOL_526:
				return ProtocolInfo::PROTOCOL_526;
			case ProtocolInfo::PROTOCOL_503:
				return ProtocolInfo::PROTOCOL_503;
			case ProtocolInfo::PROTOCOL_486:
				return ProtocolInfo::PROTOCOL_486;
			case ProtocolInfo::PROTOCOL_475:
				return ProtocolInfo::PROTOCOL_475;
			case ProtocolInfo::PROTOCOL_471:
				return ProtocolInfo::PROTOCOL_471;
			case ProtocolInfo::PROTOCOL_465:
                return ProtocolInfo::PROTOCOL_465;
			case ProtocolInfo::PROTOCOL_448:
			    return ProtocolInfo::PROTOCOL_448;
			case ProtocolInfo::PROTOCOL_440:
			    return ProtocolInfo::PROTOCOL_440;
			case ProtocolInfo::PROTOCOL_431:
			case ProtocolInfo::PROTOCOL_430:
			case ProtocolInfo::PROTOCOL_429:
			    return ProtocolInfo::PROTOCOL_429;
			case ProtocolInfo::PROTOCOL_428:
			    return ProtocolInfo::PROTOCOL_428;
			case ProtocolInfo::PROTOCOL_427:
			case ProtocolInfo::PROTOCOL_425:
			    return ProtocolInfo::PROTOCOL_425;
			case ProtocolInfo::PROTOCOL_424:
			case ProtocolInfo::PROTOCOL_423:
			case ProtocolInfo::PROTOCOL_422:
			    return ProtocolInfo::PROTOCOL_422;
			case ProtocolInfo::PROTOCOL_421:
			case ProtocolInfo::PROTOCOL_420:
			case ProtocolInfo::PROTOCOL_419:
			    return ProtocolInfo::PROTOCOL_419;
			case ProtocolInfo::PROTOCOL_418:
			case ProtocolInfo::PROTOCOL_417:
			case ProtocolInfo::PROTOCOL_416:
			case ProtocolInfo::PROTOCOL_415:
			case ProtocolInfo::PROTOCOL_414:
			case ProtocolInfo::PROTOCOL_413:
			case ProtocolInfo::PROTOCOL_412:
			case ProtocolInfo::PROTOCOL_411:
			case ProtocolInfo::PROTOCOL_410:
			case ProtocolInfo::PROTOCOL_409:
			case ProtocolInfo::PROTOCOL_408:
			    return ProtocolInfo::PROTOCOL_408;
			case ProtocolInfo::PROTOCOL_407:
			    return ProtocolInfo::PROTOCOL_407;
			case ProtocolInfo::PROTOCOL_406:
				return ProtocolInfo::PROTOCOL_406;
			case ProtocolInfo::PROTOCOL_405:
			case ProtocolInfo::PROTOCOL_404:
			case ProtocolInfo::PROTOCOL_403:
				return ProtocolInfo::PROTOCOL_403;
			case ProtocolInfo::PROTOCOL_402:
				return ProtocolInfo::PROTOCOL_402;
			case ProtocolInfo::PROTOCOL_401:
				return ProtocolInfo::PROTOCOL_401;
			case ProtocolInfo::PROTOCOL_400:
				return ProtocolInfo::PROTOCOL_400;
			case ProtocolInfo::PROTOCOL_396:
			case ProtocolInfo::PROTOCOL_395:
			case ProtocolInfo::PROTOCOL_394:
			case ProtocolInfo::PROTOCOL_393:
				return ProtocolInfo::PROTOCOL_393;
			case ProtocolInfo::PROTOCOL_392:
				return ProtocolInfo::PROTOCOL_392;
			case ProtocolInfo::PROTOCOL_391:
			case ProtocolInfo::PROTOCOL_390:
				return ProtocolInfo::PROTOCOL_390;
		    case ProtocolInfo::PROTOCOL_389:
				return ProtocolInfo::PROTOCOL_389;
			case ProtocolInfo::PROTOCOL_388:
				return ProtocolInfo::PROTOCOL_388;
			case ProtocolInfo::PROTOCOL_387:
				return ProtocolInfo::PROTOCOL_387;
			case ProtocolInfo::PROTOCOL_386:
				return ProtocolInfo::PROTOCOL_386;
			case ProtocolInfo::PROTOCOL_385:
				return ProtocolInfo::PROTOCOL_385;
			case ProtocolInfo::PROTOCOL_371:
			case ProtocolInfo::PROTOCOL_370:
				return ProtocolInfo::PROTOCOL_370;
			case ProtocolInfo::PROTOCOL_361:
				return ProtocolInfo::PROTOCOL_361;
			case ProtocolInfo::PROTOCOL_360:
				return ProtocolInfo::PROTOCOL_360;
			case ProtocolInfo::PROTOCOL_354:
			    return ProtocolInfo::PROTOCOL_354;
			case ProtocolInfo::PROTOCOL_353:
			case ProtocolInfo::PROTOCOL_352:
			case ProtocolInfo::PROTOCOL_351:
			    return ProtocolInfo::PROTOCOL_351;
			case ProtocolInfo::PROTOCOL_350:
			    return ProtocolInfo::PROTOCOL_350;
			case ProtocolInfo::PROTOCOL_342:
			    return ProtocolInfo::PROTOCOL_342;
			case ProtocolInfo::PROTOCOL_340:
			    return ProtocolInfo::PROTOCOL_340;
			case ProtocolInfo::PROTOCOL_332:
			    return ProtocolInfo::PROTOCOL_332;
			case ProtocolInfo::PROTOCOL_331:
			    return ProtocolInfo::PROTOCOL_331;
			case ProtocolInfo::PROTOCOL_330:
			    return ProtocolInfo::PROTOCOL_330;
			case ProtocolInfo::PROTOCOL_313:
			case ProtocolInfo::PROTOCOL_312:
			case ProtocolInfo::PROTOCOL_311:
			    return ProtocolInfo::PROTOCOL_311;
			case ProtocolInfo::PROTOCOL_310:
			    return ProtocolInfo::PROTOCOL_310;
			case ProtocolInfo::PROTOCOL_291:
			case ProtocolInfo::PROTOCOL_290:
			    return ProtocolInfo::PROTOCOL_290;
			case ProtocolInfo::PROTOCOL_282:
			    return ProtocolInfo::PROTOCOL_282;
			case ProtocolInfo::PROTOCOL_281:
			case ProtocolInfo::PROTOCOL_280:
			    return ProtocolInfo::PROTOCOL_280;
			case ProtocolInfo::PROTOCOL_274:
			    return ProtocolInfo::PROTOCOL_274;
			case ProtocolInfo::PROTOCOL_273:
			    return ProtocolInfo::PROTOCOL_273;
			case ProtocolInfo::PROTOCOL_271:
			    return ProtocolInfo::PROTOCOL_271;
			case ProtocolInfo::PROTOCOL_270:
			    return ProtocolInfo::PROTOCOL_270;
			case ProtocolInfo::PROTOCOL_261:
			case ProtocolInfo::PROTOCOL_260:
			    return ProtocolInfo::PROTOCOL_260;
			case ProtocolInfo::PROTOCOL_250:
			case ProtocolInfo::PROTOCOL_240:
				return ProtocolInfo::PROTOCOL_240;
			case ProtocolInfo::PROTOCOL_224:
				return ProtocolInfo::PROTOCOL_224;
			case ProtocolInfo::PROTOCOL_223:
			case ProtocolInfo::PROTOCOL_222:
			case ProtocolInfo::PROTOCOL_221:
				return ProtocolInfo::PROTOCOL_221;
			case ProtocolInfo::PROTOCOL_220:
				return ProtocolInfo::PROTOCOL_220;
			case ProtocolInfo::PROTOCOL_201:
				return ProtocolInfo::PROTOCOL_201;
			case ProtocolInfo::PROTOCOL_200:
				return ProtocolInfo::PROTOCOL_200;
			case ProtocolInfo::PROTOCOL_160:
			case ProtocolInfo::PROTOCOL_150:
			case ProtocolInfo::PROTOCOL_141:
			case ProtocolInfo::PROTOCOL_140:
			    return ProtocolInfo::PROTOCOL_140;
			case ProtocolInfo::PROTOCOL_137:
			case ProtocolInfo::PROTOCOL_136:
			case ProtocolInfo::PROTOCOL_135:
			    return ProtocolInfo::PROTOCOL_135;
			case ProtocolInfo::PROTOCOL_134:
			    return ProtocolInfo::PROTOCOL_134;
			case ProtocolInfo::PROTOCOL_133:
			    return ProtocolInfo::PROTOCOL_133;
			case ProtocolInfo::PROTOCOL_132:
				return ProtocolInfo::PROTOCOL_132;
			case ProtocolInfo::PROTOCOL_131:
			    return ProtocolInfo::PROTOCOL_131;
			case ProtocolInfo::PROTOCOL_130:
			    return ProtocolInfo::PROTOCOL_130;
			case ProtocolInfo::PROTOCOL_113:
			case ProtocolInfo::PROTOCOL_112:
			case ProtocolInfo::PROTOCOL_111:
			case ProtocolInfo::PROTOCOL_110:
			    return ProtocolInfo::PROTOCOL_110;
			case ProtocolInfo::PROTOCOL_107:
			case ProtocolInfo::PROTOCOL_106:
			case ProtocolInfo::PROTOCOL_105:
				return ProtocolInfo::PROTOCOL_105;
			case ProtocolInfo::PROTOCOL_102:
				return ProtocolInfo::PROTOCOL_102;
			case ProtocolInfo::PROTOCOL_101:
				return ProtocolInfo::PROTOCOL_101;
			case ProtocolInfo::PROTOCOL_100:
				return ProtocolInfo::PROTOCOL_100;
			case ProtocolInfo::PROTOCOL_92:
				return ProtocolInfo::PROTOCOL_92;
			case ProtocolInfo::PROTOCOL_91:
			    return ProtocolInfo::PROTOCOL_91;
			case ProtocolInfo::PROTOCOL_90:
				return ProtocolInfo::PROTOCOL_90;
			case ProtocolInfo::PROTOCOL_84:
			case ProtocolInfo::PROTOCOL_83:
			case ProtocolInfo::PROTOCOL_82:
			case ProtocolInfo::PROTOCOL_81:
				return ProtocolInfo::PROTOCOL_81;
			default:
				return ProtocolInfo::PROTOCOL_81;
		}
	}

    /**
     * @param int $playerProtocol
     * 
     * @return int
     */
	public static function convertChunkProtocol(int $playerProtocol) : int{
		switch($playerProtocol){
			case ProtocolInfo::PROTOCOL_800:
				return ProtocolInfo::PROTOCOL_800;
			case ProtocolInfo::PROTOCOL_786:
				return ProtocolInfo::PROTOCOL_786;
			case ProtocolInfo::PROTOCOL_776:
				return ProtocolInfo::PROTOCOL_776;
			case ProtocolInfo::PROTOCOL_766:
				return ProtocolInfo::PROTOCOL_766;
			case ProtocolInfo::PROTOCOL_748:
				return ProtocolInfo::PROTOCOL_748;
			case ProtocolInfo::PROTOCOL_729:
				return ProtocolInfo::PROTOCOL_729;
			case ProtocolInfo::PROTOCOL_712:
				return ProtocolInfo::PROTOCOL_712;
			case ProtocolInfo::PROTOCOL_686:
			case ProtocolInfo::PROTOCOL_685:
				return ProtocolInfo::PROTOCOL_685;
			case ProtocolInfo::PROTOCOL_671:
				return ProtocolInfo::PROTOCOL_671;
			case ProtocolInfo::PROTOCOL_662:
				return ProtocolInfo::PROTOCOL_662;
			case ProtocolInfo::PROTOCOL_649:
				return ProtocolInfo::PROTOCOL_649;
			case ProtocolInfo::PROTOCOL_630:
				return ProtocolInfo::PROTOCOL_630;
			case ProtocolInfo::PROTOCOL_622:
				return ProtocolInfo::PROTOCOL_622;
			case ProtocolInfo::PROTOCOL_618:
				return ProtocolInfo::PROTOCOL_618;
			case ProtocolInfo::PROTOCOL_594:
				return ProtocolInfo::PROTOCOL_594;
			case ProtocolInfo::PROTOCOL_589:
				return ProtocolInfo::PROTOCOL_589;
			case ProtocolInfo::PROTOCOL_582:
				return ProtocolInfo::PROTOCOL_582;
			case ProtocolInfo::PROTOCOL_575:
				return ProtocolInfo::PROTOCOL_575;
			case ProtocolInfo::PROTOCOL_568:
			case ProtocolInfo::PROTOCOL_567:
				return ProtocolInfo::PROTOCOL_567;
			case ProtocolInfo::PROTOCOL_560:
				return ProtocolInfo::PROTOCOL_560;
			case ProtocolInfo::PROTOCOL_557:
			case ProtocolInfo::PROTOCOL_553:
			case ProtocolInfo::PROTOCOL_544:
				return ProtocolInfo::PROTOCOL_544;
			case ProtocolInfo::PROTOCOL_534:
				return ProtocolInfo::PROTOCOL_534;
			case ProtocolInfo::PROTOCOL_526:
				return ProtocolInfo::PROTOCOL_526;
			case ProtocolInfo::PROTOCOL_503:
				return ProtocolInfo::PROTOCOL_503;
			case ProtocolInfo::PROTOCOL_486:
				return ProtocolInfo::PROTOCOL_486;
			case ProtocolInfo::PROTOCOL_475:
				return ProtocolInfo::PROTOCOL_475;
			case ProtocolInfo::PROTOCOL_471:
				return ProtocolInfo::PROTOCOL_471;
			case ProtocolInfo::PROTOCOL_465:
				return ProtocolInfo::PROTOCOL_465;
			case ProtocolInfo::PROTOCOL_448:
				return ProtocolInfo::PROTOCOL_448;
			case ProtocolInfo::PROTOCOL_440:
				return ProtocolInfo::PROTOCOL_440;
			case ProtocolInfo::PROTOCOL_429:
		    case ProtocolInfo::PROTOCOL_428:
				return ProtocolInfo::PROTOCOL_428;
		    case ProtocolInfo::PROTOCOL_425:
            case ProtocolInfo::PROTOCOL_422:
			case ProtocolInfo::PROTOCOL_419:
				return ProtocolInfo::PROTOCOL_419;
			case ProtocolInfo::PROTOCOL_408:
				return ProtocolInfo::PROTOCOL_408;
			case ProtocolInfo::PROTOCOL_407:
				return ProtocolInfo::PROTOCOL_407;
			case ProtocolInfo::PROTOCOL_406:
			case ProtocolInfo::PROTOCOL_403:
			case ProtocolInfo::PROTOCOL_402:
			case ProtocolInfo::PROTOCOL_401:
				return ProtocolInfo::PROTOCOL_401;
			case ProtocolInfo::PROTOCOL_400:
			case ProtocolInfo::PROTOCOL_393:
			case ProtocolInfo::PROTOCOL_392:
			case ProtocolInfo::PROTOCOL_390:
			case ProtocolInfo::PROTOCOL_389:
				return ProtocolInfo::PROTOCOL_389;
			case ProtocolInfo::PROTOCOL_388:
			case ProtocolInfo::PROTOCOL_387:
			case ProtocolInfo::PROTOCOL_386:
			case ProtocolInfo::PROTOCOL_385:
			case ProtocolInfo::PROTOCOL_370:
				return ProtocolInfo::PROTOCOL_370;
		    case ProtocolInfo::PROTOCOL_361:
			case ProtocolInfo::PROTOCOL_360:
				return ProtocolInfo::PROTOCOL_360;
			case ProtocolInfo::PROTOCOL_354:
				return ProtocolInfo::PROTOCOL_354;
			case ProtocolInfo::PROTOCOL_351:
			case ProtocolInfo::PROTOCOL_350:
			case ProtocolInfo::PROTOCOL_342:
			case ProtocolInfo::PROTOCOL_340:
				return ProtocolInfo::PROTOCOL_340;
			case ProtocolInfo::PROTOCOL_332:
			case ProtocolInfo::PROTOCOL_331:
			    return ProtocolInfo::PROTOCOL_331;
			case ProtocolInfo::PROTOCOL_330:
				return ProtocolInfo::PROTOCOL_330;
			case ProtocolInfo::PROTOCOL_311:
			case ProtocolInfo::PROTOCOL_310:
			    return ProtocolInfo::PROTOCOL_310;
			case ProtocolInfo::PROTOCOL_290:
				return ProtocolInfo::PROTOCOL_290;
			case ProtocolInfo::PROTOCOL_282:
			case ProtocolInfo::PROTOCOL_280:
			    return ProtocolInfo::PROTOCOL_280;
			case ProtocolInfo::PROTOCOL_274:
				return ProtocolInfo::PROTOCOL_274;
			case ProtocolInfo::PROTOCOL_273:
			case ProtocolInfo::PROTOCOL_271:
			case ProtocolInfo::PROTOCOL_270:
			    return ProtocolInfo::PROTOCOL_270;
			case ProtocolInfo::PROTOCOL_260:
				return ProtocolInfo::PROTOCOL_260;
			case ProtocolInfo::PROTOCOL_240:
				return ProtocolInfo::PROTOCOL_240;
			case ProtocolInfo::PROTOCOL_224:
			case ProtocolInfo::PROTOCOL_221:
				return ProtocolInfo::PROTOCOL_221;
			case ProtocolInfo::PROTOCOL_220:
				return ProtocolInfo::PROTOCOL_220;
			case ProtocolInfo::PROTOCOL_201:
			case ProtocolInfo::PROTOCOL_200:
			case ProtocolInfo::PROTOCOL_140:
			case ProtocolInfo::PROTOCOL_135:
			case ProtocolInfo::PROTOCOL_134:
			case ProtocolInfo::PROTOCOL_133:
			case ProtocolInfo::PROTOCOL_132:
			case ProtocolInfo::PROTOCOL_131:
			case ProtocolInfo::PROTOCOL_130:
			    return ProtocolInfo::PROTOCOL_130;
			case ProtocolInfo::PROTOCOL_110:
			    return ProtocolInfo::PROTOCOL_110;
			case ProtocolInfo::PROTOCOL_105:
				return ProtocolInfo::PROTOCOL_105;
			case ProtocolInfo::PROTOCOL_102:
			case ProtocolInfo::PROTOCOL_101:
			case ProtocolInfo::PROTOCOL_100:
				return ProtocolInfo::PROTOCOL_100;
			case ProtocolInfo::PROTOCOL_92:
				return ProtocolInfo::PROTOCOL_92;
			case ProtocolInfo::PROTOCOL_91:
			    return ProtocolInfo::PROTOCOL_91;
			case ProtocolInfo::PROTOCOL_90:
				return ProtocolInfo::PROTOCOL_90;
			case ProtocolInfo::PROTOCOL_81:
				return ProtocolInfo::PROTOCOL_81;
			default:
				return ProtocolInfo::PROTOCOL_81;
		}
	}

    /**
     * @param int $playerProtocol
     * 
     * @return int
     */
	public static function convertCraftingProtocol(int $playerProtocol) : int{
		switch($playerProtocol){
			case ProtocolInfo::PROTOCOL_800:
				return ProtocolInfo::PROTOCOL_800;
			case ProtocolInfo::PROTOCOL_786:
				return ProtocolInfo::PROTOCOL_786;
			case ProtocolInfo::PROTOCOL_776:
				return ProtocolInfo::PROTOCOL_776;
			case ProtocolInfo::PROTOCOL_766:
				return ProtocolInfo::PROTOCOL_766;
			case ProtocolInfo::PROTOCOL_748:
				return ProtocolInfo::PROTOCOL_748;
			case ProtocolInfo::PROTOCOL_729:
				return ProtocolInfo::PROTOCOL_729;
			case ProtocolInfo::PROTOCOL_712:
                return ProtocolInfo::PROTOCOL_712;
			case ProtocolInfo::PROTOCOL_686:
			case ProtocolInfo::PROTOCOL_685:
			    return ProtocolInfo::PROTOCOL_685;
			case ProtocolInfo::PROTOCOL_671:
			    return ProtocolInfo::PROTOCOL_671;
			case ProtocolInfo::PROTOCOL_662:
			    return ProtocolInfo::PROTOCOL_662;
			case ProtocolInfo::PROTOCOL_649:
			    return ProtocolInfo::PROTOCOL_649;
			case ProtocolInfo::PROTOCOL_630:
			    return ProtocolInfo::PROTOCOL_630;
			case ProtocolInfo::PROTOCOL_622:
			    return ProtocolInfo::PROTOCOL_622;
			case ProtocolInfo::PROTOCOL_618:
				return ProtocolInfo::PROTOCOL_618;
			case ProtocolInfo::PROTOCOL_594:
				return ProtocolInfo::PROTOCOL_594;
			case ProtocolInfo::PROTOCOL_589:
				return ProtocolInfo::PROTOCOL_589;
			case ProtocolInfo::PROTOCOL_582:
				return ProtocolInfo::PROTOCOL_582;
			case ProtocolInfo::PROTOCOL_575:
			    return ProtocolInfo::PROTOCOL_575;
			case ProtocolInfo::PROTOCOL_568:
			case ProtocolInfo::PROTOCOL_567:
			    return ProtocolInfo::PROTOCOL_567;
			case ProtocolInfo::PROTOCOL_560:
			    return ProtocolInfo::PROTOCOL_560;
			case ProtocolInfo::PROTOCOL_557:
			case ProtocolInfo::PROTOCOL_553:
			    return ProtocolInfo::PROTOCOL_553;
			case ProtocolInfo::PROTOCOL_544:
			    return ProtocolInfo::PROTOCOL_544;
			case ProtocolInfo::PROTOCOL_534:
			    return ProtocolInfo::PROTOCOL_534;
			case ProtocolInfo::PROTOCOL_526:
			    return ProtocolInfo::PROTOCOL_526;
			case ProtocolInfo::PROTOCOL_503:
				return ProtocolInfo::PROTOCOL_503;
			case ProtocolInfo::PROTOCOL_486:
				return ProtocolInfo::PROTOCOL_486;
			case ProtocolInfo::PROTOCOL_475:
			    return ProtocolInfo::PROTOCOL_475;
			case ProtocolInfo::PROTOCOL_471:
			    return ProtocolInfo::PROTOCOL_471;
			case ProtocolInfo::PROTOCOL_465:
			    return ProtocolInfo::PROTOCOL_465;
			case ProtocolInfo::PROTOCOL_448:
			    return ProtocolInfo::PROTOCOL_448;
			case ProtocolInfo::PROTOCOL_440:
			    return ProtocolInfo::PROTOCOL_440;
			case ProtocolInfo::PROTOCOL_429:
			    return ProtocolInfo::PROTOCOL_429;
		    case ProtocolInfo::PROTOCOL_428:
		        return ProtocolInfo::PROTOCOL_428;
		    case ProtocolInfo::PROTOCOL_425:
		    case ProtocolInfo::PROTOCOL_422:
			case ProtocolInfo::PROTOCOL_419:
			    return ProtocolInfo::PROTOCOL_419;
			case ProtocolInfo::PROTOCOL_408:
				return ProtocolInfo::PROTOCOL_408;
			case ProtocolInfo::PROTOCOL_407:
			case ProtocolInfo::PROTOCOL_406:
				return ProtocolInfo::PROTOCOL_406;
			case ProtocolInfo::PROTOCOL_403:
				return ProtocolInfo::PROTOCOL_403;
			case ProtocolInfo::PROTOCOL_402:
				return ProtocolInfo::PROTOCOL_402;
			case ProtocolInfo::PROTOCOL_401:
			    return ProtocolInfo::PROTOCOL_401;
			case ProtocolInfo::PROTOCOL_400:
			case ProtocolInfo::PROTOCOL_393:
			case ProtocolInfo::PROTOCOL_392:
			    return ProtocolInfo::PROTOCOL_392;
			case ProtocolInfo::PROTOCOL_390:
			case ProtocolInfo::PROTOCOL_389:
				return ProtocolInfo::PROTOCOL_389;
			case ProtocolInfo::PROTOCOL_388:
			case ProtocolInfo::PROTOCOL_387:
			case ProtocolInfo::PROTOCOL_386:
			case ProtocolInfo::PROTOCOL_385:
			    return ProtocolInfo::PROTOCOL_385;
			case ProtocolInfo::PROTOCOL_370:
		    case ProtocolInfo::PROTOCOL_361:
				return ProtocolInfo::PROTOCOL_361;
			case ProtocolInfo::PROTOCOL_360:
				return ProtocolInfo::PROTOCOL_360;
			case ProtocolInfo::PROTOCOL_354:
			case ProtocolInfo::PROTOCOL_351:
			case ProtocolInfo::PROTOCOL_350:
			    return ProtocolInfo::PROTOCOL_350;
			case ProtocolInfo::PROTOCOL_342:
			case ProtocolInfo::PROTOCOL_340:
				return ProtocolInfo::PROTOCOL_340;
			case ProtocolInfo::PROTOCOL_332:
			case ProtocolInfo::PROTOCOL_331:
			    return ProtocolInfo::PROTOCOL_331;
			case ProtocolInfo::PROTOCOL_330:
			    return ProtocolInfo::PROTOCOL_330;
			case ProtocolInfo::PROTOCOL_311:
			case ProtocolInfo::PROTOCOL_310:
			    return ProtocolInfo::PROTOCOL_310;
			case ProtocolInfo::PROTOCOL_290:
			case ProtocolInfo::PROTOCOL_282:
			case ProtocolInfo::PROTOCOL_280:
			    return ProtocolInfo::PROTOCOL_280;
			case ProtocolInfo::PROTOCOL_274:
			case ProtocolInfo::PROTOCOL_273:
			case ProtocolInfo::PROTOCOL_271:
			case ProtocolInfo::PROTOCOL_270:
			case ProtocolInfo::PROTOCOL_260:
				return ProtocolInfo::PROTOCOL_260;
			case ProtocolInfo::PROTOCOL_240:
			case ProtocolInfo::PROTOCOL_224:
			case ProtocolInfo::PROTOCOL_221:
			case ProtocolInfo::PROTOCOL_220:
			case ProtocolInfo::PROTOCOL_201:
			case ProtocolInfo::PROTOCOL_200:
			case ProtocolInfo::PROTOCOL_140:
			case ProtocolInfo::PROTOCOL_135:
			case ProtocolInfo::PROTOCOL_134:
				return ProtocolInfo::PROTOCOL_134;
			case ProtocolInfo::PROTOCOL_133:
			case ProtocolInfo::PROTOCOL_132:
			case ProtocolInfo::PROTOCOL_131:
			case ProtocolInfo::PROTOCOL_130:
			    return ProtocolInfo::PROTOCOL_130;
			case ProtocolInfo::PROTOCOL_110:
			    return ProtocolInfo::PROTOCOL_110;
			case ProtocolInfo::PROTOCOL_105:
				return ProtocolInfo::PROTOCOL_105;
			case ProtocolInfo::PROTOCOL_102:
			case ProtocolInfo::PROTOCOL_101:
			case ProtocolInfo::PROTOCOL_100:
				return ProtocolInfo::PROTOCOL_100;
			case ProtocolInfo::PROTOCOL_92:
				return ProtocolInfo::PROTOCOL_92;
			case ProtocolInfo::PROTOCOL_91:
			    return ProtocolInfo::PROTOCOL_91;
			case ProtocolInfo::PROTOCOL_90:
				return ProtocolInfo::PROTOCOL_90;
			case ProtocolInfo::PROTOCOL_81:
				return ProtocolInfo::PROTOCOL_81;
			default:
				return ProtocolInfo::PROTOCOL_81;
		}
	}
}