<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *
*/

declare(strict_types=1);

namespace pocketmine\network\mcpe\multiversion\constants;

use pocketmine\network\mcpe\protocol\ProtocolInfo;

final class PlayerActionIds{
	private function __construct(){
		//NOOP
	}

	public const PLAYER_ACTION_IDS = [
        ProtocolInfo::PROTOCOL_748 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_CREATIVE_PLAYER_DESTROY_BLOCK' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25,
	        'ACTION_PREDICT_DESTROY_BLOCK' => 26,
	        'ACTION_CONTINUE_DESTROY_BLOCK' => 27,
	        'ACTION_START_ITEM_USE_ON' => 28,
	        'ACTION_STOP_ITEM_USE_ON' => 29,
	        'ACTION_HANDLED_TELEPORT' => 30,
            'ACTION_MISSED_SWING' => 31,
            'ACTION_START_CRAWLING' => 32,
            'ACTION_STOP_CRAWLING' => 33,
            'ACTION_START_FLYING' => 34,
            'ACTION_STOP_FLYING' => 35,
            'ACTION_ACK_ACTOR_DATA' => 36,
            'ACTION_START_USING_ITEM' => 37
        ],
        ProtocolInfo::PROTOCOL_622 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_CREATIVE_PLAYER_DESTROY_BLOCK' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25,
	        'ACTION_PREDICT_DESTROY_BLOCK' => 26,
	        'ACTION_CONTINUE_DESTROY_BLOCK' => 27,
	        'ACTION_START_ITEM_USE_ON' => 28,
	        'ACTION_STOP_ITEM_USE_ON' => 29,
	        'ACTION_HANDLED_TELEPORT' => 30,
            'ACTION_MISSED_SWING' => 31,
            'ACTION_START_CRAWLING' => 32,
            'ACTION_STOP_CRAWLING' => 33,
            'ACTION_START_FLYING' => 34,
            'ACTION_STOP_FLYING' => 35,
            'ACTION_ACK_ACTOR_DATA' => 36
        ],
        ProtocolInfo::PROTOCOL_618 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_CREATIVE_PLAYER_DESTROY_BLOCK' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25,
	        'ACTION_PREDICT_DESTROY_BLOCK' => 26,
	        'ACTION_CONTINUE_DESTROY_BLOCK' => 27,
	        'ACTION_START_ITEM_USE_ON' => 28,
	        'ACTION_STOP_ITEM_USE_ON' => 29,
	        'ACTION_HANDLED_TELEPORT' => 30,
            'ACTION_MISSED_SWING' => 31,
            'ACTION_START_CRAWLING' => 32,
            'ACTION_STOP_CRAWLING' => 33,
            'ACTION_START_FLYING' => 34,
            'ACTION_STOP_FLYING' => 35
        ],
        ProtocolInfo::PROTOCOL_594 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_CREATIVE_PLAYER_DESTROY_BLOCK' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25,
	        'ACTION_PREDICT_DESTROY_BLOCK' => 26,
	        'ACTION_CONTINUE_DESTROY_BLOCK' => 27,
	        'ACTION_START_ITEM_USE_ON' => 28,
	        'ACTION_STOP_ITEM_USE_ON' => 29,
	        'ACTION_HANDLED_TELEPORT' => 30,
            'ACTION_MISSED_SWING' => 31,
            'ACTION_START_CRAWLING' => 32,
            'ACTION_STOP_CRAWLING' => 33
        ],
        ProtocolInfo::PROTOCOL_567 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_CREATIVE_PLAYER_DESTROY_BLOCK' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25,
	        'ACTION_PREDICT_DESTROY_BLOCK' => 26,
	        'ACTION_CONTINUE_DESTROY_BLOCK' => 27,
	        'ACTION_START_ITEM_USE_ON' => 28,
	        'ACTION_STOP_ITEM_USE_ON' => 29,
	        'ACTION_HANDLED_TELEPORT' => 30
        ],
        ProtocolInfo::PROTOCOL_526 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_CREATIVE_PLAYER_DESTROY_BLOCK' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25,
	        'ACTION_PREDICT_DESTROY_BLOCK' => 26,
	        'ACTION_CONTINUE_DESTROY_BLOCK' => 27,
	        'ACTION_START_ITEM_USE_ON' => 28,
	        'ACTION_STOP_ITEM_USE_ON' => 29
        ],
        ProtocolInfo::PROTOCOL_428 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_CREATIVE_PLAYER_DESTROY_BLOCK' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25,
	        'ACTION_PREDICT_DESTROY_BLOCK' => 26,
	        'ACTION_CONTINUE_DESTROY_BLOCK' => 27
        ],
        ProtocolInfo::PROTOCOL_419 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_CREATIVE_PLAYER_DESTROY_BLOCK' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25
        ],
        ProtocolInfo::PROTOCOL_134 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_START_SLEEPING' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_DIMENSION_CHANGE_REQUEST' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18,
            'ACTION_CHANGE_SKIN' => 19,
            'ACTION_SET_ENCHANTMENT_SEED' => 20,
            'ACTION_START_SWIMMING' => 21,
            'ACTION_STOP_SWIMMING' => 22,
            'ACTION_START_SPIN_ATTACK' => 23,
            'ACTION_STOP_SPIN_ATTACK' => 24,
            'ACTION_INTERACT_BLOCK' => 25
        ],
        ProtocolInfo::PROTOCOL_130 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_STOP_SLEEPING' => 5,
            'ACTION_RESPAWN' => 6,
            'ACTION_JUMP' => 7,
            'ACTION_START_SPRINT' => 8,
            'ACTION_STOP_SPRINT' => 9,
            'ACTION_START_SNEAK' => 10,
            'ACTION_STOP_SNEAK' => 11,
            'ACTION_DIMENSION_CHANGE_REQUEST' => 12,
            'ACTION_DIMENSION_CHANGE_ACK' => 13,
            'ACTION_START_GLIDE' => 14,
            'ACTION_STOP_GLIDE' => 15,
            'ACTION_BUILD_DENIED' => 16,
            'ACTION_CONTINUE_BREAK' => 17,
            'ACTION_SET_ENCHANTMENT_SEED' => 19,
            'ACTION_RELEASE_ITEM' => 99999
        ],
        ProtocolInfo::PROTOCOL_81 => [
            'ACTION_START_BREAK' => 0,
            'ACTION_ABORT_BREAK' => 1,
            'ACTION_STOP_BREAK' => 2,
            'ACTION_GET_UPDATED_BLOCK' => 3,
            'ACTION_DROP_ITEM' => 4,
            'ACTION_RELEASE_ITEM' => 5,
            'ACTION_STOP_SLEEPING' => 6,
            'ACTION_RESPAWN' => 7,
            'ACTION_JUMP' => 8,
            'ACTION_START_SPRINT' => 9,
            'ACTION_STOP_SPRINT' => 10,
            'ACTION_START_SNEAK' => 11,
            'ACTION_STOP_SNEAK' => 12,
            'ACTION_DIMENSION_CHANGE_REQUEST' => 13,
            'ACTION_DIMENSION_CHANGE_ACK' => 14,
            'ACTION_START_GLIDE' => 15,
            'ACTION_STOP_GLIDE' => 16,
            'ACTION_BUILD_DENIED' => 17,
            'ACTION_CONTINUE_BREAK' => 18
        ]
	];
}
